version: '3.3'
services:
  insumos-microservicio:
    build: ./microservicio
    ports:
     - "3069:3069"
    depends_on:
     - insumos-db
    environment:
     - DATABASE_HOST=insumos-db
  insumos-db:
    build: ./database